name: Build, Lint and Test

on: [pull_request, push]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install dependency
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
